In [3]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv('Advertising.csv')

In [7]:
df

Unnamed: 0     TV  radio  newspaper  sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [8]:
df.head()

Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [11]:
df.columns

Index(['Unnamed: 0', 'TV', 'radio', 'newspaper', 'sales'], dtype='object')

In [15]:
df.values

array([[  1. , 230.1,  37.8,  69.2,  22.1],
       [  2. ,  44.5,  39.3,  45.1,  10.4],
       [  3. ,  17.2,  45.9,  69.3,   9.3],
       [  4. , 151.5,  41.3,  58.5,  18.5],
       [  5. , 180.8,  10.8,  58.4,  12.9],
       [  6. ,   8.7,  48.9,  75. ,   7.2],
       [  7. ,  57.5,  32.8,  23.5,  11.8],
       [  8. , 120.2,  19.6,  11.6,  13.2],
       [  9. ,   8.6,   2.1,   1. ,   4.8],
       [ 10. , 199.8,   2.6,  21.2,  10.6],
       [ 11. ,  66.1,   5.8,  24.2,   8.6],
       [ 12. , 214.7,  24. ,   4. ,  17.4],
       [ 13. ,  23.8,  35.1,  65.9,   9.2],
       [ 14. ,  97.5,   7.6,   7.2,   9.7],
       [ 15. , 204.1,  32.9,  46. ,  19. ],
       [ 16. , 195.4,  47.7,  52.9,  22.4],
       [ 17. ,  67.8,  36.6, 114. ,  12.5],
       [ 18. , 281.4,  39.6,  55.8,  24.4],
       [ 19. ,  69.2,  20.5,  18.3,  11.3],
       [ 20. , 147.3,  23.9,  19.1,  14.6],
       [ 21. , 218.4,  27.7,  53.4,  18. ],
       [ 22. , 237.4,   5.1,  23.5,  12.5],
       [ 23. ,  13.2,  15.9,  49

In [17]:
df.shape

(200, 5)

In [21]:
df.describe()

Unnamed: 0          TV       radio   newspaper       sales
count  200.000000  200.000000  200.000000  200.000000  200.000000
mean   100.500000  147.042500   23.264000   30.554000   14.022500
std     57.879185   85.854236   14.846809   21.778621    5.217457
min      1.000000    0.700000    0.000000    0.300000    1.600000
25%     50.750000   74.375000    9.975000   12.750000   10.375000
50%    100.500000  149.750000   22.900000   25.750000   12.900000
75%    150.250000  218.825000   36.525000   45.100000   17.400000
max    200.000000  296.400000   49.600000  114.000000   27.000000

In [24]:
df.isna()

Unnamed: 0     TV  radio  newspaper  sales
0         False  False  False      False  False
1         False  False  False      False  False
2         False  False  False      False  False
3         False  False  False      False  False
4         False  False  False      False  False
..          ...    ...    ...        ...    ...
195       False  False  False      False  False
196       False  False  False      False  False
197       False  False  False      False  False
198       False  False  False      False  False
199       False  False  False      False  False

[200 rows x 5 columns]

In [35]:
df.drop('Unnamed: 0',axis=1)
# this error occur because of column is already droped

KeyError: "['Unnamed: 0'] not found in axis"

In [36]:
df

TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [34]:
df1 = df[['TV','radio','newspaper','sales']]
df1.head()


TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [37]:
df1.isna().sum()

TV           0
radio        0
newspaper    0
sales        0
dtype: int64

In [41]:
from sklearn.model_selection import train_test_split as tts

In [111]:
X=df1[['TV']]
Y=df1[['sales']]
X1 = df1[['radio']]
Y1 = df1[['newspaper']]


In [79]:
x_train, x_test, y_train, y_test = tts(X,Y,random_state=101) #train is used to fit data and test is used to evaluate data

In [80]:
x_train.shape

(150, 1)

In [81]:
 x_test.shape

(50, 1)

In [82]:
y_train.shape

(150, 1)

In [83]:
y_test.shape

(50, 1)

In [84]:
from sklearn.linear_model import LinearRegression as lr

In [85]:
my_model = lr()

In [86]:
my_model.fit(x_train,y_train) # here we fit x&y train in module

LinearRegression()

In [87]:
m =my_model.coef_

In [88]:
c = my_model.intercept_

In [89]:
y = (m*230.1)+c
y

array([[17.8667296]])

In [93]:
my_model.predict([[230.1]]) #model can directly predict without equation

D:\Anaconda\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[17.8667296]])

In [95]:
my_model.fit(x_test,y_test)

LinearRegression()

In [96]:
m1 = my_model.coef_

In [97]:
c1 = my_model.intercept_

In [100]:
y1 = (m1*230.1)+c1
y1

array([[18.36889101]])

In [104]:
k = my_model.predict(x_test)

In [105]:
from sklearn.metrics import mean_squared_error,mean_absolute_error

In [107]:
mean_squared_error(k,y_test)

9.433250880580987

In [108]:
mean_absolute_error(k,y_test)

2.374920125130063

In [112]:
#exmaples for when we use MSE and MAE
x1_train, x1_test, y1_train, y1_test = tts(X1,Y1,random_state=101) #train is used to fit data and test is used to evaluate data

In [113]:
my_model.fit(x1_train,y1_train)

LinearRegression()

In [127]:
k1 = my_model.predict(x1_train)

In [128]:
mean_squared_error(k1,x1_train)

84.53313585881713

In [129]:
mean_absolute_error(k1,x1_train)

8.530323288774632

In [141]:
my_model.fit(x1_test,y1_test)

LinearRegression()

In [142]:
k2 = my_model.predict(x1_test)
k3 = my_model.predict(y1_test)

D:\Anaconda\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- newspaper
Feature names seen at fit time, yet now missing:
- radio

  warnings.warn(message, FutureWarning)


In [143]:
mean_squared_error(k2,x1_test)

85.37893248075653